module ViewMP exposing (..)

import Browser exposing (..)
import Browser.Events exposing (onResize)
import Dict exposing (update)
import Html as H exposing (..)
import Html.Attributes as HA exposing (..)
import Html.Events as HE exposing (..)
import Message as M exposing (..)


viewAll =
    div []
        [ H.p [ id "t1" ]
            [ H.text "Age of Plague"
            , br [] []
            ]
        , H.p [ id "t2" ] [ H.text "After the Apocalypse" ]
        , div [ class "container" ]
            [ div [ class "honeycomb " ]
                [ div [ class "column" ]
                    [ a [ class "hex", id "tut1", HE.onClick (M.LevelBegin 1) ]
                        [ div [ class "wrapper" ]
                            [ div [ class "hexagon color-1" ]
                                []
                            ]
                        , span [ class "content" ]
                            [ strong []
                                [ text "Tutorial1" ]
                            ]
                        ]
                    , a [ class "hex", id "tut2", HE.onClick (M.LevelBegin 2) ]
                        [ div [ class "wrapper" ]
                            [ div [ class "hexagon color-1" ]
                                []
                            ]
                        , span [ class "content" ]
                            [ strong []
                                [ text "Tutorial2" ]
                            ]
                        ]
                    , a [ class "hex", id "city1", HE.onClick (M.LevelBegin 3) ]
                        [ div [ class "wrapper" ]
                            [ div [ class "hexagon color-1" ]
                                []
                            ]
                        , span [ class "content" ]
                            [ strong []
                                [ text "City 1" ]
                            ]
                        ]
                    , a [ class "hex", id "city2", HE.onClick (M.LevelBegin 4) ]
                        [ div [ class "wrapper" ]
                            [ div [ class "hexagon color-1" ]
                                []
                            ]
                        , span [ class "content" ]
                            [ strong []
                                [ text "City 2" ]
                            ]
                        ]
                    , a [ class "hex", id "city3", HE.onClick (M.LevelBegin 5) ]
                        [ div [ class "wrapper" ]
                            [ div [ class "hexagon color-1" ]
                                []
                            ]
                        , span [ class "content" ]
                            [ strong []
                                [ text "City 3" ]
                            ]
                        ]
                    , a [ class "hex", id "endless", HE.onClick (M.LevelBegin 6) ]
                        [ div [ class "wrapper" ]
                            [ div [ class "hexagon color-1" ]
                                []
                            ]
                        , span [ class "content" ]
                            [ strong []
                                [ text "Endless" ]
                            ]
                        ]
                    , a [ class "hex", id "gallery", HE.onClick (M.Click "card") ]
                        [ div [ class "wrapper" ]
                            [ div [ class "hexagon color-1" ]
                                []
                            ]
                        , span [ class "content" ]
                            [ strong []
                                [ text "Gallery" ]
                            ]
                        ]
                    ]
                , div [ class "shadows" ]
                    []
                ]
            ]
        ]
