module ViewCards exposing (..)

import Browser exposing (..)
import Browser.Events exposing (..)
import Html as H exposing (..)
import Html.Attributes as HA exposing (..)
import Html.Events as HE exposing (..)


viewCard : List (Html msg)
viewCard =
    [ h1 [] [ text "Cards Gallery" ]
    , div [ class "wrapper" ]
        [ div [ class "container", id "c1", attribute "data-info" "+3 power, next round -3 power" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "Power Overload" ]
                    ]
                ]
            ]
        , div [ class "container", id "c2", attribute "data-info" "+2 power" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "On Standby" ]
                    ]
                ]
            ]
        , div [ class "container", id "c3", attribute "data-info" "There is a probability of 50% to freeze the spread of viruses spread for 1 round." ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "Cold Wave" ]
                    ]
                ]
            ]
        , div [ class "container", id "c4", attribute "data-info" "Freeze the spread of viruses spread for 3 rounds." ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "Blizzard" ]
                    ]
                ]
            ]
        , div [ class "container", id "c5", attribute "data-info" "In two rounds, there is a probability of 50% to freeze the spread of viruses for 1 round. The economy output doubles for two rounds." ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "Rain" ]
                    ]
                ]
            ]
        , div [ class "container", id "c6", attribute "data-info" "Cut the virus on one hexagon." ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "Cut" ]
                    ]
                ]
            ]
        , div [ class "container", id "c7", attribute "data-info" "The next 2 rounds, economy temporarily doubles, but the death rate permanently rises 5%." ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "996" ]
                    ]
                ]
            ]
        , div [ class "container", id "c8", attribute "data-info" "Cut the virus on one tile." ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "Mega Cut" ]
                    ]
                ]
            ]
        , div [ class "container", id "c9" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "9" ]
                    , p []
                        [ text "9" ]
                    ]
                ]
            ]
        , div [ class "container", id "c10" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "10" ]
                    , p []
                        [ text "10" ]
                    ]
                ]
            ]
        , div [ class "container", id "c11" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "11" ]
                    , p []
                        [ text "11" ]
                    ]
                ]
            ]
        , div [ class "container", id "c12" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "12" ]
                    , p []
                        [ text "12" ]
                    ]
                ]
            ]
        , div [ class "container", id "c13" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "13" ]
                    , p []
                        [ text "13" ]
                    ]
                ]
            ]
        , div [ class "container", id "c14" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "14" ]
                    , p []
                        [ text "14" ]
                    ]
                ]
            ]
        , div [ class "container", id "c15" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "15" ]
                    , p []
                        [ text "15" ]
                    ]
                ]
            ]
        , div [ class "container", id "c16" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "16" ]
                    , p []
                        [ text "16" ]
                    ]
                ]
            ]
        , div [ class "container", id "c17" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "17" ]
                    , p []
                        [ text "17" ]
                    ]
                ]
            ]
        , div [ class "container", id "c18" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "18" ]
                    , p []
                        [ text "18" ]
                    ]
                ]
            ]
        , div [ class "container", id "c19" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "19" ]
                    , p []
                        [ text "19" ]
                    ]
                ]
            ]
        , div [ class "container", id "c20" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "20" ]
                    , p []
                        [ text "20" ]
                    ]
                ]
            ]
        , div [ class "container", id "c21" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "21" ]
                    , p []
                        [ text "21" ]
                    ]
                ]
            ]
        , div [ class "container", id "c22" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "22" ]
                    , p []
                        [ text "22" ]
                    ]
                ]
            ]
        , div [ class "container", id "c23" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "23" ]
                    , p []
                        [ text "23" ]
                    ]
                ]
            ]
        , div [ class "container", id "c24" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "24" ]
                    , p []
                        [ text "24" ]
                    ]
                ]
            ]
        , div [ class "container", id "c25" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "25" ]
                    , p []
                        [ text "25" ]
                    ]
                ]
            ]
        , div [ class "container", id "c26" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "26" ]
                    , p []
                        [ text "26" ]
                    ]
                ]
            ]
        , div [ class "container", id "c27" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "27" ]
                    , p []
                        [ text "27" ]
                    ]
                ]
            ]
        , div [ class "container", id "c28" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "28" ]
                    , p []
                        [ text "28" ]
                    ]
                ]
            ]
        , div [ class "container", id "c29" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "29" ]
                    , p []
                        [ text "29" ]
                    ]
                ]
            ]
        , div [ class "container", id "c30" ]
            [ div [ class "image" ]
                []
            , div [ class "story" ]
                [ div [ class "info" ]
                    [ h3 []
                        [ text "30" ]
                    , p []
                        [ text "30" ]
                    ]
                ]
            ]
        ]
    ]
