module ViewMP exposing (..)

import Browser exposing (..)
import Browser.Events exposing (onResize)
import Dict exposing (update)
import Html as H exposing (..)
import Html.Attributes as HA exposing (..)
import Html.Events as HE exposing (..)
import Message as M exposing (..)


viewAll =
    div [ class "container" ]
        [ H.p [ id "t1" ]
            [ H.text "Age of Plague"
            , br [] []
            ]
        , H.p [ id "t2" ] [ H.text "After the Apocalypse" ]
        , div [ class "honeycomb " ]
            [ div [ class "column" ]
                [ a [ class "hex", id "level", HE.onClick (M.Click "tutorial") ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "Tutorial" ]
                        , small []
                            [ text "i'm a hexagon" ]
                        ]
                    ]
                , a [ class "hex", id "gallery", HE.onClick (M.Click "card") ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "Gallery" ]
                        , small []
                            [ text "i'm a hexagon" ]
                        ]
                    ]
                , a [ class "hex", id "c1" ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "City 1" ]
                        , small []
                            [ text "i'm a hexagon" ]
                        ]
                    ]
                , a [ class "hex", id "c2" ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "City 2" ]
                        , small []
                            [ text "i'm a hexagon" ]
                        ]
                    ]
                , a [ class "hex", id "c3" ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "City 3" ]
                        , small []
                            [ text "i'm a hexagon" ]
                        ]
                    ]
                , a [ class "hex", id "endless" ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "Endless" ]
                        , small []
                            [ text "i'm a hexagon" ]
                        ]
                    ]
                ]
            , div [ class "shadows" ]
                []
            ]
        ]
