module ViewMP exposing (..)

import Html as H exposing (..)
import Html.Attributes as HA exposing (..)
import Html.Events as HE exposing (..)
import Message as M exposing (..)


viewAll =
    [ H.p [ id "t1" ]
        [ H.text "Age of Plague"
        , br [] []
        ]
    , H.p [ id "t2" ] [ H.text "After the Apocalypse" ]
    , div [ class "container", id "ctr" ]
        [ div [ class "honeycomb " ]
            [ div [ class "column" ]
                [ a [ class "hex", id "tut1", HE.onClick (M.LevelBegin 1) ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "Tutorial1" ]
                        ]
                    ]
                , a [ class "hex", id "tut2", HE.onClick (M.LevelBegin 2) ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "Tutorial2" ]
                        ]
                    ]
                , a [ class "hex", id "city1", HE.onClick (M.LevelBegin 3) ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "Atlanta" ]
                        ]
                    ]
                , a [ class "hex", id "city2", HE.onClick (M.LevelBegin 4) ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "Amber" ]
                        ]
                    ]
                , a [ class "hex", id "city3", HE.onClick (M.LevelBegin 5) ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "St.Petersburg" ]
                        ]
                    ]
                , a [ class "hex", id "endless", HE.onClick (M.LevelBegin 6) ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "Endless" ]
                        ]
                    ]
                , a [ class "hex", id "gallery", HE.onClick (M.Click "card") ]
                    [ div [ class "wrapper" ]
                        [ div [ class "hexagon color-1" ]
                            []
                        ]
                    , span [ class "content" ]
                        [ strong []
                            [ text "Collection" ]
                        ]
                    ]
                ]
            , div [ class "shadows" ]
                []
            ]
        ]
    , H.span [ HA.id "About" ] [ H.text "Team LJWZ© presents" ]
    , H.audio
        [ HA.id "bgm"
        , HA.src "./assets/music/bgm1.mp3"
        , HA.loop True
        ]
        []
    ]
